services:
  - type: web
    name: casca-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
